#!/usr/bin/perl -w

use strict;
use warnings;

use CGI;
use Template;

use lib qw(./lib);
use IdleRPG::Config;


my $template_path   = 'index.tt';

my $cgi             = CGI->new;
my $config          = IdleRPG::Config::get_config();
my $template        = Template->new(ABSOLUTE => 'f');

main();

sub main {
    my $html = $cgi->header();
    $template->process( $template_path, {
            irpg_page_title => 'Game Info',
            baseurl         => $config->baseurl(),
            irpg_logo       => $config->logo(),
            irpg_bot        => $config->botname(),
            irpg_server     => $config->server(),
            irpg_chan       => $config->botchan(),
        }, \$html) || die;
    print $html;
}
